### ISSUE TITLE
SimpleBungee 1.1.1 not working

### ISSUE THREAD

**Issue by larssieboy18** [Jackzmc/SimpleBungee#1]
Hi,

SimpleBungee produces an error on startup. Here is the error log: https://pastebin.com/zZi592QK. Is there anything that you can do about it? If you need any more info, just let me know!
There is also an error while closing the server: https://pastebin.com/qFY3w1N9

Best regards,
Lars

**Comment by Jackzmc** [comment]
I think I fixed it in the latest version, you can download the development one here:
https://ci.jackz.me/job/SimpleBungee/lastSuccessfulBuild/artifact/target/SimpleBungee-1.0-SNAPSHOT.jar

Tell me if that fixes it

**Comment by Jackzmc** [comment]
I have setup my local test server and I can confirm this. May I ask if you are running on linux or windows?
